//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string StudentRollNo { get; set; }
        public string StudentDepartment { get; set; }
        public string StudentBatchNo { get; set; }
        public string StudentYear { get; set; }
    }
}
